In [3]:
# Ejercicio 1: Crear un array de 10 elementos con ceros
import numpy as np

array_ceros = np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Ejercicio 2: Generar un array con los números del 1 al 20
array_1_20 = np.arange(1, 21)
print(array_1_20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# Ejercicio 3: Crear un array con los números pares del 2 al 50
array_pares = np.arange(2, 51, 2)
print(array_pares)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [6]:
# Ejercicio 4: Crear una matriz de 4x4 con valores aleatorios entre 0 y 1
matriz = np.random.rand(4, 4)
print(matriz)

[[0.57134526 0.9222254  0.3510897  0.25081355]
 [0.82061183 0.40877602 0.50846884 0.55377603]
 [0.13982777 0.9023803  0.51584904 0.95306836]
 [0.67240499 0.03156946 0.21396315 0.33865917]]


In [7]:
# Ejercicio 5: Suma elemento a elemento de dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


In [9]:
# Ejercicio 6: Multiplicar dos matrices 3x3 de enteros aleatorios entre 1 y 10
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))

producto = np.dot(A, B)
print(producto)

[[135 130 122]
 [147  96 142]
 [ 70  39 116]]


In [10]:
# Ejercicio 7: Crear un array de 15 valores aleatorios entre 1 y 100
array = np.random.randint(1, 101, 15)

print("Array:", array)
print("Máximo:", np.max(array))
print("Mínimo:", np.min(array))
print("Promedio:", np.mean(array))

Array: [ 45  96  17  76 100  46  23  54  47  10  99  49  65  83  39]
Máximo: 100
Mínimo: 10
Promedio: 56.6


In [11]:
# Ejercicio 8: Generar una matriz 5x5 del 1 al 25 y extraer su diagonal
matriz = np.arange(1, 26).reshape(5, 5)

diagonal = np.diag(matriz)

print("Matriz:\n", matriz)
print("Diagonal:", diagonal)

Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


In [12]:
# Ejercicio 9: Matriz 5x5 aleatoria y suma por filas y columnas
matriz = np.random.randint(1, 21, (5, 5))

suma_filas = matriz.sum(axis=1)
suma_columnas = matriz.sum(axis=0)

print("Matriz:\n", matriz)
print("Suma por filas:", suma_filas)
print("Suma por columnas:", suma_columnas)

Matriz:
 [[17 15 12  2  8]
 [ 4 14 18 13 15]
 [ 5 17  5  1 18]
 [12 10  7  8  7]
 [ 1 16 18  2 19]]
Suma por filas: [54 64 46 44 56]
Suma por columnas: [39 72 60 26 67]
